#!/usr/bin/env bash
set -euo pipefail
: "${PG_ADMIN_URL:?Set PG_ADMIN_URL}"
: "${ISNOTREAL_OWNER_PASSWORD:?Set ISNOTREAL_OWNER_PASSWORD}"
: "${ISNOTREAL_APP_PASSWORD:?Set ISNOTREAL_APP_PASSWORD}"
: "${ISNOTREAL_EDITOR_PASSWORD:?Set ISNOTREAL_EDITOR_PASSWORD}"
DB_NAME="${ISNOTREAL_DB_NAME:-isnotreal}"
OWNER="${ISNOTREAL_OWNER_ROLE:-isnotreal_owner}"
APP="${ISNOTREAL_APP_ROLE:-isnotreal_app}"
EDITOR="${ISNOTREAL_EDITOR_ROLE:-isnotreal_editor}"
q(){ printf "%s" "$1" | sed "s/\047/\047\047/g"; }
OPW="$(q "$ISNOTREAL_OWNER_PASSWORD")"; APW="$(q "$ISNOTREAL_APP_PASSWORD")"; EPW="$(q "$ISNOTREAL_EDITOR_PASSWORD")"
psql "$PG_ADMIN_URL" -v ON_ERROR_STOP=1 <<SQL
DO \\$\\$
BEGIN
 IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname=\047$OWNER\047) THEN CREATE ROLE $OWNER LOGIN PASSWORD \047$OPW\047 NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION; ELSE ALTER ROLE $OWNER PASSWORD \047$OPW\047; END IF;
 IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname=\047$APP\047) THEN CREATE ROLE $APP LOGIN PASSWORD \047$APW\047 NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION; ELSE ALTER ROLE $APP PASSWORD \047$APW\047; END IF;
 IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname=\047$EDITOR\047) THEN CREATE ROLE $EDITOR LOGIN PASSWORD \047$EPW\047 NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION; ELSE ALTER ROLE $EDITOR PASSWORD \047$EPW\047; END IF;
END \\$\\$;
SQL
if ! psql "$PG_ADMIN_URL" -Atqc "select 1 from pg_database where datname=\047$DB_NAME\047" | grep -q 1; then psql "$PG_ADMIN_URL" -v ON_ERROR_STOP=1 -c "CREATE DATABASE $DB_NAME OWNER $OWNER"; fi
echo "Roles/database ready. Run migrations as $OWNER, then ops/db-grants.sh."
